export const ERRORPAGE = '/errorpage'
export const SHOWALLMOVIES = '/showallmovies'
export const COMPAREMOVIES = '/comparemovies'
export const COMPARECHARACTERS = '/comparecharacters'
export const WINNERPAGE = '/winnerpage'